# Generated by Django 4.1.1 on 2022-09-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
