# Generated by Django 4.1.1 on 2022-09-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0002_alter_subscribe_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
