# Generated by Django 4.1.1 on 2022-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0003_alter_subscribe_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribe",
            name="newsletter",
            field=models.EmailField(
                choices=[("M", "Monthly"), ("W", "Weekly")], default="W", max_length=2
            ),
            preserve_default=False,
        ),
    ]
