# Generated by Django 4.1.1 on 2022-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0004_subscribe_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="newsletter",
            field=models.EmailField(
                choices=[("M", "Monthly"), ("W", "Weekly")], default="M", max_length=2
            ),
        ),
    ]
