# Generated by Django 4.1.1 on 2022-09-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_location_jobpost_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="slug",
            field=models.SlugField(max_length=45, null=True, unique=True),
        ),
    ]
