# Generated by Django 4.1.1 on 2022-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_author_jobpost_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
