# Generated by Django 4.1.1 on 2022-09-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="skill",
            field=models.ManyToManyField(to="app.skill"),
        ),
    ]
