# Generated by Django 4.1.1 on 2022-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_jobpost_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="type",
            field=models.CharField(
                choices=[("Full Time", "Full Time"), ("Part Time", "Part Time")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobpost", name="description", field=models.TextField(),
        ),
    ]
