# Generated by Django 4.1.1 on 2022-09-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploadapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Upload", new_name="Uploads",),
    ]
