# Generated by Django 4.1.1 on 2022-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadapp", "0002_rename_upload_uploads"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files")),
                ("description", models.CharField(max_length=100)),
            ],
        ),
    ]
